/**
 * Curated default cable profile catalog (plan §20).
 *
 * These are planning defaults only: realistic connectors, signal families,
 * standard stocked lengths (canonical meters) and realistic linear weights.
 * Projects may override or extend this catalog; nothing here is inferred from
 * model names (AGENTS.md rule 28).
 */

import type { CableProfile } from './types';

export const DEFAULT_CABLE_PROFILES: CableProfile[] = [
  {
    id: 'cable-sdi-12g-bnc',
    name: 'SDI 12G coax (BNC–BNC)',
    connectorA: 'BNC',
    connectorB: 'BNC',
    supportedSignalTypes: ['SDI', 'GENLOCK', 'TIMECODE'],
    standardLengthsM: [1, 5, 10, 25, 50, 100],
    weightPerMeterKg: 0.075,
    notes: 'RG-6 style 12G-SDI coax, 4K60 capable up to ~70m.',
  },
  {
    id: 'cable-sdi-3g-bnc',
    name: 'SDI 3G coax (BNC–BNC)',
    connectorA: 'BNC',
    connectorB: 'BNC',
    supportedSignalTypes: ['SDI', 'GENLOCK', 'TIMECODE'],
    standardLengthsM: [1, 5, 10, 20, 30, 50],
    weightPerMeterKg: 0.055,
    notes: 'RG-59 style 3G-SDI coax, HD/3G up to ~100m.',
  },
  {
    id: 'cable-hdmi-aoc',
    name: 'HDMI 2.0 cable',
    connectorA: 'HDMI',
    connectorB: 'HDMI',
    supportedSignalTypes: ['HDMI_VIDEO'],
    standardLengthsM: [1, 2, 3, 5, 10, 15],
    weightPerMeterKg: 0.09,
    notes: 'Passive copper up to 3m; active/optical for longer runs.',
  },
  {
    id: 'cable-smpte-hybrid-fiber',
    name: 'SMPTE 311M hybrid camera fiber',
    connectorA: 'SMPTE_FIBER',
    connectorB: 'SMPTE_FIBER',
    supportedSignalTypes: ['SMPTE_CAMERA', 'SDI', 'INTERCOM', 'TIMECODE'],
    standardLengthsM: [20, 30, 50, 100, 200],
    weightPerMeterKg: 0.13,
    notes: 'Hybrid fiber + copper power for CCUs; carries camera power, video, tally, comms.',
  },
  {
    id: 'cable-tactical-fiber-lc',
    name: 'Tactical fiber (LC–LC, OM4)',
    connectorA: 'LC_FIBER',
    connectorB: 'LC_FIBER',
    supportedSignalTypes: ['SDI', 'SMPTE_ST2110', 'ETHERNET', 'NDI'],
    standardLengthsM: [10, 20, 50, 100],
    weightPerMeterKg: 0.045,
    notes: 'Tactical fiber with reinforced jacket for signal extension/conversion.',
  },
  {
    id: 'cable-ethernet-cat6',
    name: 'Ethernet Cat6 (RJ45–RJ45)',
    connectorA: 'RJ45',
    connectorB: 'RJ45',
    supportedSignalTypes: ['ETHERNET', 'DANTE', 'AES67', 'ARTNET', 'SACN', 'NDI'],
    standardLengthsM: [0.5, 1, 2, 5, 10, 20, 30, 50],
    weightPerMeterKg: 0.04,
    notes: 'Cat6 U/UTP patch; 100m channel limit including patch leads.',
  },
  {
    id: 'cable-dmx-xlr5',
    name: 'DMX512 data (XLR5–XLR5)',
    connectorA: 'XLR5',
    connectorB: 'XLR5',
    supportedSignalTypes: ['DMX512'],
    standardLengthsM: [1, 5, 10, 25],
    weightPerMeterKg: 0.045,
    notes: '110Ω data cable; 32-fixture drop limit per universe segment.',
  },
  {
    id: 'cable-audio-xlr3',
    name: 'Analog audio (XLR3–XLR3)',
    connectorA: 'XLR3',
    connectorB: 'XLR3',
    supportedSignalTypes: ['ANALOG_AUDIO', 'INTERCOM', 'TIMECODE'],
    standardLengthsM: [1, 3, 5, 10, 20, 30],
    weightPerMeterKg: 0.06,
    notes: 'Balanced mic/line level cable.',
  },
  {
    id: 'cable-aes3-xlr3',
    name: 'AES3 digital audio (XLR3–XLR3)',
    connectorA: 'XLR3',
    connectorB: 'XLR3',
    supportedSignalTypes: ['AES_EBU'],
    standardLengthsM: [1, 2, 5, 10],
    weightPerMeterKg: 0.06,
    notes: '110Ω balanced digital audio; keep runs under ~100m.',
  },
  {
    id: 'cable-speaker-speakon',
    name: 'Speaker cable (speakON–speakON)',
    connectorA: 'SPEAKON',
    connectorB: 'SPEAKON',
    supportedSignalTypes: ['SPEAKER_LEVEL'],
    standardLengthsM: [5, 10, 15, 20, 30],
    weightPerMeterKg: 0.11,
    notes: '2×2.5mm² speaker cable for passive PA tops/subs.',
  },
  {
    id: 'cable-socapex',
    name: 'Multicore lighting (Socapex–Socapex)',
    connectorA: 'SOCAPEX',
    connectorB: 'SOCAPEX',
    supportedSignalTypes: ['POWER_AC'],
    standardLengthsM: [5, 10, 20, 25],
    weightPerMeterKg: 0.62,
    notes: '19-pin 6-circuit dimmer/hot-power multicore, 16A per circuit.',
  },
  {
    id: 'cable-true1',
    name: 'Mains power (powerCON TRUE1)',
    connectorA: 'POWERCON_TRUE1',
    connectorB: 'POWERCON_TRUE1',
    supportedSignalTypes: ['POWER_AC'],
    standardLengthsM: [1, 3, 5, 10],
    weightPerMeterKg: 0.15,
    notes: '16A locking mains connector, hot-pluggable.',
  },
  {
    id: 'cable-schuko',
    name: 'Mains extension (Schuko–Schuko)',
    connectorA: 'SCHUKO',
    connectorB: 'SCHUKO',
    supportedSignalTypes: ['POWER_AC'],
    standardLengthsM: [3, 5, 10, 20, 30, 50],
    weightPerMeterKg: 0.24,
    notes: '16A Schuko extension lead, 3×1.5mm² H07RN-F.',
  },
  {
    id: 'cable-cee16',
    name: 'Power distro (CEE16 blue)',
    connectorA: 'CEE16',
    connectorB: 'CEE16',
    supportedSignalTypes: ['POWER_AC'],
    standardLengthsM: [10, 20, 25, 50],
    weightPerMeterKg: 0.55,
    notes: '230V 16A single-phase blue CEE, 3×2.5mm².',
  },
  {
    id: 'cable-cee32',
    name: 'Power distro (CEE32 red)',
    connectorA: 'CEE32',
    connectorB: 'CEE32',
    supportedSignalTypes: ['POWER_AC'],
    standardLengthsM: [10, 20, 25, 50],
    weightPerMeterKg: 0.95,
    notes: '400V 32A three-phase red CEE, 5×4mm².',
  },
  {
    id: 'cable-cee63',
    name: 'Power distro (CEE63 red)',
    connectorA: 'CEE63',
    connectorB: 'CEE63',
    supportedSignalTypes: ['POWER_AC'],
    standardLengthsM: [10, 20, 25],
    weightPerMeterKg: 1.7,
    notes: '400V 63A three-phase red CEE, 5×16mm².',
  },
];
